### ISSUE TITLE
Handle telegram's flaky API connection

### ISSUE THREAD

**Issue by SathyaBhat** [SathyaBhat/tumibot#1]
Telegram API randomly dies out

```
~/tumibot# /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/http.rb:933:in `connect_nonblock': Connection reset by peer - SSL_connect (Errno::ECONNRESET)
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/http.rb:933:in `connect'
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/http.rb:852:in `start'
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/http.rb:1398:in `request'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/httparty-0.14.0/lib/httparty/request.rb:118:in `perform'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/httparty-0.14.0/lib/httparty.rb:560:in `perform_request'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/httparty-0.14.0/lib/httparty.rb:486:in `get'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/httparty-0.14.0/lib/httparty.rb:598:in `get'
        from tumibot.rb:84:in `<main>'
```

This needs to be handled suitably

**Comment by SathyaBhat** [comment]
fixed in https://github.com/SathyaBhat/tumibot/commit/57a4d0959960fc23cf4d9d956ef1d56a49803983
