### ISSUE TITLE
Can't run  db-setup 

### ISSUE THREAD

**Issue by Axelfoley85** [SathyaBhat/tumibot#2]
Hey SathyaBhat,

I am a total newbie with ruby. I was just curious what was your bot about and tried it. Maybe you have some advice. I ran into trouble installing your bot and got following mistake. I tried to setup. I have Ubuntu 16.04 and just followed your instructions. Let my know if you have some advice :)

Cheers,
Axel

```
$ ruby db-setup.rb
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- sequel (LoadError)
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from db-setup.rb:1:in `<main>'
```

**Comment by SathyaBhat** [comment]
Hi @Axelfoley85 

have you done a 

     bundle install

Can you paste the results after running these: 

    gem install bundler
    bundle install

Cheers

**Comment by Axelfoley85** [comment]
Hey Sathya, thanks for your effort! There is several mistakes. I am now trying to follow the steps recommended.

- install brew
- brew install sqlite3

------------------------------------------------------------------
```
sudo gem install bundler
sudo bundle install

Successfully installed bundler-1.15.1
Parsing documentation for bundler-1.15.1
Done installing documentation for bundler after 4 seconds
1 gem installed
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Fetching gem metadata from https://rubygems.org/............
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Using multi_xml 0.6.0
Using sequel 4.47.0
Fetching sqlite3 1.3.13
Installing sqlite3 1.3.13 with native extensions
Using bundler 1.15.1
Using httparty 0.15.5
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/sqlite3-1.3.13/ext/sqlite3
/usr/bin/ruby2.3 -r ./siteconf20170602-16799-k6jkwn.rb extconf.rb
checking for sqlite3.h... no
sqlite3.h is missing. Try 'brew install sqlite3',
'yum install sqlite-devel' or 'apt-get install libsqlite3-dev'
and check your shared library search path (the
location where your sqlite3 shared library is located).
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/$(RUBY_BASE_NAME)2.3
	--with-sqlite3-config
	--without-sqlite3-config
	--with-pkg-config
	--without-pkg-config
	--with-sqlite3-dir
	--without-sqlite3-dir
	--with-sqlite3-include
	--without-sqlite3-include=${sqlite3-dir}/include
	--with-sqlite3-lib
	--without-sqlite3-lib=${sqlite3-dir}/lib

To see why this extension failed to compile, please check the mkmf.log which can
be found here:

  /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/sqlite3-1.3.13/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/sqlite3-1.3.13 for
inspection.
Results logged to
/var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/sqlite3-1.3.13/gem_make.out


An error occurred while installing sqlite3 (1.3.13), and Bundler cannot
continue.
Make sure that `gem install sqlite3 -v '1.3.13'` succeeds before bundling.

In Gemfile:
  sqlite3
```

**Comment by Axelfoley85** [comment]
succesfull:
```
sudo apt install linuxbrew-wrapper

ok. I am new to Ubuntu and getting stuck here:

brew install sqlite3

========================================================================
You may want to update following environments after installed linuxbrew.

  PATH, MANPATH, INFOPATH 

(example: /usr/share/doc/linuxbrew-wrapper/examples/profile)

========================================================================
==> This script will install:
/home/axelfoley/.linuxbrew/bin/brew
/home/axelfoley/.linuxbrew/Library/...
/home/axelfoley/.linuxbrew/share/man/man1/brew.1

Press RETURN to continue or any other key to abort
==> Downloading and installing Homebrew...
remote: Counting objects: 353405, done.
remote: Total 353405 (delta 0), reused 0 (delta 0), pack-reused 353405
Receiving objects: 100% (353405/353405), 67.84 MiB | 2.66 MiB/s, done.
Resolving deltas: 100% (267197/267197), done.
From https://github.com/Homebrew/linuxbrew
 * [new branch]      master     -> origin/master
HEAD is now at eec5059 Merge branch homebrew/master into linuxbrew/master
Warning: /home/axelfoley/.linuxbrew/bin is not in your PATH.
==> Installation successful!
==> Next steps
Install the Linuxbrew dependencies:

Debian, Ubuntu, etc.:
  `sudo apt-get install build-essential`

Fedora, Red Hat, CentOS, etc.:
  `sudo yum groupinstall 'Development Tools'`

See http://brew.sh/linuxbrew/#dependencies for more information.

Run `brew doctor` before you install anything
Run `brew help` to get started
==> Tapping homebrew/dupes
Cloning into '/home/axelfoley/.linuxbrew/Library/Taps/homebrew/homebrew-dupes'...
remote: Counting objects: 5, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 5 (delta 0), reused 3 (delta 0), pack-reused 0
Unpacking objects: 100% (5/5), done.
Checking connectivity... done.
Tapped 0 formulae (29 files, 111.9K)
Error: No available formula with the name "homebrew/dupes/unzip" (dependency of sqlite)
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.
```

**Comment by SathyaBhat** [comment]
hi @Axelfoley85 you don't need to install (home)brew or brew wrappers. 

I would recommend removing it

    sudo apt remove linuxbrew-wrapper

Then run these:

    sudo apt-get install ruby2.3-dev build-essential
    gem install bundler
    bundle install


Let me know what happens after you run these
